#!/usr/bin/env sh
# Setup script for initial environment configuration

set -e

echo "🔧 Setting up containerized CI/CD environment..."

# Check if Docker is available
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    exit 1
fi

# Check if Docker daemon is running
if ! docker info &> /dev/null; then
    echo "❌ Docker daemon is not running. Please start Docker."
    exit 1
fi

echo "✅ Docker is available"

# Create .env file from .env.example if it doesn't exist
if [ ! -f .env ]; then
    echo "📝 Creating .env file from .env.example..."
    cp .env.example .env
    echo "⚠️  Please edit .env file and update the secrets before running the pipeline"
else
    echo "✅ .env file already exists"
fi

# Create empty poetry.lock if needed (will be populated by Poetry)
if [ ! -s poetry.lock ]; then
    echo "📝 Creating empty poetry.lock file..."
    echo "# This file is @generated by Poetry and should be committed to source control." > poetry.lock
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Edit .env file with your configuration"
echo "  2. Run the CI pipeline: docker compose run --rm ci-builder"
echo "  3. Or start development: docker compose up -d db cache app"
echo ""
